services:
  aphw-ddi-portal:
    build:
      context: .
      target: production
    image: aphw-ddi-portal
    container_name: aphw-ddi-portal
    environment:
      APPINSIGHTS_CLOUDROLE: aphw-ddi-portal-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      DDA_INDEX_API_BASE_URL: ${DDA_INDEX_API_BASE_URL:-test}
      OS_PLACES_API_KEY: ${OS_PLACES_API_KEY:-test}
      OS_PLACES_API_BASE_URL: ${OS_PLACES_API_BASE_URL:-test}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      AZUREID_CLIENT_SECRET: ${AZUREID_CLIENT_SECRET}
      AZUREID_CLIENT_ID: ${AZUREID_CLIENT_ID}
      AZUREID_TENANT_ID: ${AZUREID_TENANT_ID}
      REDIRECT_URL: ${REDIRECT_URL}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_CREATE_CONTAINERS: "true"
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-test}

  aphw-ddi-portal-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
    command: "azurite-blob --skipApiVersionCheck --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: aphw-ddi-portal-azurite
