# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  aphw-ddi-portal:
    build:
      target: development
    image: aphw-ddi-portal-development
    container_name: aphw-ddi-portal-test
    command: npm run test
    volumes:
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
    depends_on: 
      - aphw-ddi-portal-azurite
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://aphw-ddi-portal-azurite:10000/devstoreaccount1;TableEndpoint=http://aphw-ddi-portal-azurite:10002/devstoreaccount1;"
      DDI_API_BASE_URL: test
      DDI_EVENTS_BASE_URL: test-events
      NODE_OPTIONS: "--max-old-space-size=3072"

  aphw-ddi-portal-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.23.0
