services:
  aphw-ddi-pact-postgres:
    image: postgres:11.22-alpine
    environment:
      POSTGRES_DB: aphw-ddi-pact
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: pact
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    volumes:
      - pact_postgres_data:/var/lib/postgres/data
  aphw-ddi-pact-broker:
    image: pactfoundation/pact-broker:2.117.1-pactbroker2.109.1-multi
    depends_on:
      - aphw-ddi-pact-postgres
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_DATABASE_ADAPTER: 'postgres'
      PACT_BROKER_DATABASE_USERNAME: 'postgres'
      PACT_BROKER_DATABASE_PASSWORD: 'pact'
      PACT_BROKER_DATABASE_HOST: 'aphw-ddi-pact-postgres'
      PACT_BROKER_DATABASE_NAME: 'aphw-ddi-pact'
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
volumes:
  pact_postgres_data: