# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  aphw-ddi-portal:
    build:
      target: development
    image: aphw-ddi-portal-development
    container_name: aphw-ddi-portal-development
    ports:
      - "3002:3000"
      - "9231:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10000/devstoreaccount1;}
