Feature: Create new interim exemption with multiple dogs

    Scenario: Add 3 dogs to the same owner
        Given I open the url "/"
        When I click on the link containing "Process new CDO or"
        And I set "James" to the inputfield "#firstName"
        And I set "Gunn" to the inputfield "#lastName"
        And I set "03" to the inputfield "#dateOfBirth-day"
        And I set "03" to the inputfield "#dateOfBirth-month"
        And I set "1980" to the inputfield "#dateOfBirth-year"
        And I click on the element "button=Continue"
        And I set "NN1 1ES" to the inputfield "#postcode"
        And I set "60" to the inputfield "#houseNumber"
        And I click on the element "button=Continue"
        And I click on the element "button=Confirm address"
        And I set "345677654344444" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Rex" to the inputfield "#name"
        And I select the radio option with the value "interim-exemption" from the radio group "applicationType"
        And I set "01" to the inputfield "#interimExemption-day"
        And I set "02" to the inputfield "#interimExemption-month"
        And I set "2024" to the inputfield "#interimExemption-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "345677654355555" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Pit Bull Terrier" from the radio group "breed"
        And I set "Dino" to the inputfield "#name"
        And I select the radio option with the value "interim-exemption" from the radio group "applicationType"
        And I set "01" to the inputfield "#interimExemption-day"
        And I set "02" to the inputfield "#interimExemption-month"
        And I set "2024" to the inputfield "#interimExemption-year"
        And I click on the element "button=Add dog details"
        And I click on the element "button=Add another dog for this owner"
        And I set "345677654366666" to the inputfield "#microchipNumber"
        And I click on the element "button=Continue"
        And I select the radio option with the value "Japanese Tosa" from the radio group "breed"
        And I set "Maxie" to the inputfield "#name"
        And I select the radio option with the value "interim-exemption" from the radio group "applicationType"
        And I set "01" to the inputfield "#interimExemption-day"
        And I set "02" to the inputfield "#interimExemption-month"
        And I set "2024" to the inputfield "#interimExemption-year"
        And I click on the element "button=Add dog details"
        Then I expect that element "h1" contains the text "Confirm dog details"
        And I expect that element "(//dd)[1]" contains the text "XL Bully"
        And I expect that element "(//dd)[2]" contains the text "Rex"
        And I expect that element "(//dd)[3]" contains the text "345677654344444"
        And I expect that element "(//dd)[4]" contains the text "01 February 2024"
        And I expect that element "(//dd)[5]" contains the text "Pit Bull Terrier"
        And I expect that element "(//dd)[6]" contains the text "Dino"
        And I expect that element "(//dd)[7]" contains the text "345677654355555"
        And I expect that element "(//dd)[8]" contains the text "01 February 2024"
        And I expect that element "(//dd)[9]" contains the text "Japanese Tosa"
        And I expect that element "(//dd)[10]" contains the text "Maxie"
        And I expect that element "(//dd)[11]" contains the text "345677654366666"
        And I expect that element "(//dd)[12]" contains the text "01 February 2024"


    Scenario: Delete dog
        When I click on the link containing "Delete"
        And I click on the element "button=Delete dog details"
        Then I expect that element "h1" contains the text "Confirm dog details"
        And I expect that element "(//dd)[1]" contains the text "Pit Bull Terrier"
        And I expect that element "(//dd)[2]" contains the text "Dino"
        And I expect that element "(//dd)[3]" contains the text "345677654355555"
        And I expect that element "(//dd)[4]" contains the text "01 February 2024"
        And I expect that element "(//dd)[5]" contains the text "Japanese Tosa"
        And I expect that element "(//dd)[6]" contains the text "Maxie"
        And I expect that element "(//dd)[7]" contains the text "345677654366666"
        And I expect that element "(//dd)[8]" contains the text "01 February 2024"

    Scenario: Enter enforcement details and Confirm all details
        And I click on the element "button=Confirm details"
        And I set "Declan" to the inputfield "#legislationOfficer"
        And I click on the element "button=Continue"
        Then I expect that element "h1" contains the text "Confirm all details"
        And I expect that element "(//dd)[1]" contains the text "James Gunn"
        And I expect that element "(//dd)[3]" contains the text "03 March 1980"
        And I expect that element "(//dd)[5]" contains the text "NN1 1ES"
        And I expect that element "(//dd)[7]" contains the text "England"
        And I expect that element "(//dd)[8]" contains the text "Northamptonshire Police"
        And I expect that element "(//dd)[9]" contains the text "Declan"
        And I expect that element "(//dd)[11]" contains the text "Pit Bull Terrier"
        And I expect that element "(//dd)[12]" contains the text "Dino"
        And I expect that element "(//dd)[13]" contains the text "345677654355555"
        And I expect that element "(//dd)[14]" contains the text "01 February 2024"
        And I expect that element "(//dd)[15]" contains the text "Japanese Tosa"
        And I expect that element "(//dd)[16]" contains the text "Maxie"
        And I expect that element "(//dd)[17]" contains the text "345677654366666"
        And I expect that element "(//dd)[18]" contains the text "01 February 2024"

    Scenario: Interim exemption record created successfully with multiple dogs
        And I click on the element "button=Confirm details"
        Then I expect that element "h1" contains the text "Record created" 
        And I expect that element "(//dd)[1]" contains the text "Pit Bull Terrier"
        And I expect that element "(//dd)[2]" contains the text "Dino"
        And I expect that element "(//dd)[3]" contains the text "345677654355555"
        And I expect that element "(//dd)[4]" contains the text "01 February 2024"
        And I expect that element "(//dd)[5]" contains the text "Japanese Tosa"
        And I expect that element "(//dd)[6]" contains the text "Maxie"
        And I expect that element "(//dd)[7]" contains the text "345677654366666"
        And I expect that element "(//dd)[8]" contains the text "01 February 2024"
        And I expect that element "(//dd)[9]" contains the text "James Gunn"
        And I expect that element "(//dd)[10]" contains the text "03 March 1980"
        And I expect that element "(//dd)[11]" contains the text "NN1 1ES"
        And I expect that element "(//dd)[12]" contains the text "England"
        And I expect that element "(//dd)[13]" contains the text "Northamptonshire Police"