Feature: Create new record validations

    Scenario: Mandatory information missing on owner details
        Given I open the url "/"
        When I click on the link "Create new record"
        And I click on the element "button=Find address"
        Then I expect that element "form" contains the text "Enter a first name"
        And I expect that element "form" contains the text "Enter a last name"
        And I expect that element "form" contains the text "Enter a postcode"

    Scenario: Owner DOB in future
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I set "01" to the inputfield "#owner-date-of-birth-dobDay"
        And I set "02" to the inputfield "#owner-date-of-birth-dobMonth"
        And I set "2028" to the inputfield "#owner-date-of-birth-dobYear"
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I click on the element "button=Find address"
        Then I expect that element "form" contains the text "Date of birth must be in the past"  

    Scenario: Owner is less than 16 years old
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I set "01" to the inputfield "#owner-date-of-birth-dobDay"
        And I set "02" to the inputfield "#owner-date-of-birth-dobMonth"
        And I set "2023" to the inputfield "#owner-date-of-birth-dobYear"
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I click on the element "button=Find address"
        Then I expect that element "form" contains the text "The dog owner must be aged 16 or over"               

    Scenario: Mandatory information missing on manually enter address details
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I click on the element "button=Enter address manually"
        And I click on the element "button=Continue"
        Then I expect that element "form" contains the text "Enter the first line of the address"
        And I expect that element "form" contains the text "Enter the town or city"
        And I expect that element "form" contains the text "Enter a postcode"

    Scenario: Mandatory information missing on add dog details
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I set "12" to the inputfield "#houseNumber"
        And I click on the element "button=Find address"
        And I click on the element "button=Confirm address"
        And I click on the element "button=Add dog details"
        Then I expect that element "form" contains the text "Breed type is required"
        And I expect that element "form" contains the text "Application type is required"

    Scenario: CDO Issue date validations
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I set "12" to the inputfield "#houseNumber"
        And I click on the element "button=Find address"
        And I click on the element "button=Confirm address"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Fido" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I click on the element "button=Add dog details"
        Then I expect that element "form" contains the text "Enter a CDO issue date"

    Scenario: CDO Issue date in future
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I set "12" to the inputfield "#houseNumber"
        And I click on the element "button=Find address"
        And I click on the element "button=Confirm address"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Fido" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "01" to the inputfield "#cdoIssued-day"
        And I set "02" to the inputfield "#cdoIssued-month"
        And I set "2028" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        Then I expect that element "form" contains the text "Enter a date that is today or in the past"

    Scenario: Invalid CDO Issue date
        Given I open the url "/"
        When I click on the link "Create new record"
        And I set "John" to the inputfield "#firstName"
        And I set "Smith" to the inputfield "#lastName"
        And I set "LS20 8DA" to the inputfield "#postcode"
        And I set "12" to the inputfield "#houseNumber"
        And I click on the element "button=Find address"
        And I click on the element "button=Confirm address"
        And I select the radio option with the value "XL Bully" from the radio group "breed"
        And I set "Fido" to the inputfield "#name"
        And I select the radio option with the value "cdo" from the radio group "applicationType"
        And I set "31" to the inputfield "#cdoIssued-day"
        And I set "04" to the inputfield "#cdoIssued-month"
        And I set "2023" to the inputfield "#cdoIssued-year"
        And I click on the element "button=Add dog details"
        Then I expect that element "form" contains the text "Enter a real date"           