#!/usr/bin/env sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

service="wdio-cucumber"

echo $projectRoot

export TEST_ENVIRONMENT_ROOT_URL=http://host.docker.internal:3002
export JAVA_HOME=/usr/libexec/java_home

docker-compose run --rm ${service}
#docker-compose -f docker-compose.yaml -f docker-compose.override.yaml -p "${service}"