{{- include "ffc-helm-library.container-config-map" (list . "aphw-ddi-portal.config-map") -}}
{{- define "aphw-ddi-portal.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.pr }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}-{{ .Values.pr }}.{{ .Values.ingress.server }}/{{ .Values.azureAppRegistration.redirectUrl }}
  {{ else }}
  REDIRECT_URL: https://{{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}/{{ .Values.azureAppRegistration.redirectUrl }}
  {{- end }}
  AUTHENTICATION_ENABLED: {{ quote .Values.azureAppRegistration.enabled }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
{{- end -}}
