{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-portal.container-secret") -}}
{{- define "aphw-ddi-portal.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  OS_PLACES_API_KEY: {{ .Values.container.osPlacesApiKey | quote }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
{{- end -}}
