{{- include "ffc-helm-library.container-secret" (list . "aphw-ddi-portal.container-secret") -}}
{{- define "aphw-ddi-portal.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  AZUREID_CLIENT_SECRET: {{ quote .Values.azureAppRegistration.clientSecret }}
  AZUREID_CLIENT_ID: {{ quote .Values.azureAppRegistration.clientId }}
  AZUREID_TENANT_ID: {{ quote .Values.azureAppRegistration.tenantId }}
  AZURE_STORAGE_CONNECTION_STRING: {{ quote .Values.container.azureStorageConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  COOKIE_PASSWORD: {{ quote .Values.container.cookiePassword }}
  OS_PLACES_API_KEY: {{ .Values.container.osPlacesApiKey | quote }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  MESSAGE_QUEUE_PASSWORD: {{ quote .Values.container.messageQueuePassword }}
  MESSAGE_QUEUE_USER: {{ quote .Values.container.messageQueueUser }}
{{- end -}}
