{{- include "ffc-helm-library.horizontal-pod-autoscaler" (list . "aphw-ddi-portal.horizontal-pod-autoscaler") -}}
{{- define "aphw-ddi-portal.horizontal-pod-autoscaler" -}}
spec:  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.deployment.cpuThreshold }}
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: {{ .Values.deployment.memoryThreshold }}
{{- end -}}