#!/usr/bin/env sh

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker compose -f ../docker-compose.test.contract.yaml -p "ddi-contract-pact-broker" up
