apiVersion: v2
description: Web frontend for managing the dogs index
name: dangerous-dogs-act-portal
# this version is automatically updated in the build pipeline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 3.4.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
