#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

. "${projectRoot}/.env"

docker compose down

docker compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  up --no-recreate $@
